### ISSUE TITLE
youtube queries throw a configuration error

### ISSUE THREAD

**Issue by aschlow** [omardelarosa/hubot-c3po#3]
"c3poBOT [3:41 PM] 
You must configure the HUBOT_YOUTUBE_API_KEY environment variable"

**Comment by omardelarosa** [comment]
@aschlow Want to register (and then volunteer your) API key? https://github.com/hubot-scripts/hubot-youtube

**Comment by aschlow** [comment]
I have the key, now what?

**Comment by omardelarosa** [comment]
@aschlow private message it to me and I will set it to that variable on heroku.

**Comment by omardelarosa** [comment]
done.
